// GENERATED FILE — do not edit by hand.
//
// Regenerate with `python tool/gen_bank_directory.py`, which reads the
// DLT sender-header registry in `list_of_banks.txt` and collapses its
// filing names into one display name per bank. See BankDirectory in
// `bank_directory.dart` for how a sender is resolved against this.
library;

/// Display name -> every DLT sender header registered to that bank.
///
/// 610 banks across 1525 headers.
const Map<String, List<String>> kHeadersByBank = {
  'AU Small Finance Bank': [
    '120012', '121200', '180012', '181200', '181212', 'AUBANK', 'AUBMSG',
    'AUBSMS', 'AUDOST', 'AUITSM',
  ],
  'Abhyudaya Co-operative Bank': ['ACBLBK'],
  'Ad Shamraoji Shinde Satyashodhak Sahakari Bank Kolhapur': ['SATBNK'],
  'Adarsh Co-operative Bank': ['ADRBNK'],
  'Adarsha Pattana Souharda Sahakari Bank Niyamita': ['APSSBN'],
  'Agra Zila Sahkari Bank': ['AGRABK', 'ZSAGRA'],
  'Airtel Payments Bank': [
    '171717', '177177', '650017', '650137', 'AIRBNK', 'AIRBSE', 'AIRBSI',
  ],
  'Akhand Anand Co-operative Bank': ['AKHAND'],
  'Alappuzha District Co-operative Bank': ['TADCBK'],
  'Alavi Co-operative Bank': ['ALVIBK'],
  'Allahabad Bank': ['ALBANK'],
  'Almora Zila Sahkari Bank': ['ALMABK', 'ALMORA'],
  'Ambajogai Peoples Co-operative Bank Ambajogai': ['APCBNK'],
  'American Express Banking': [
    'AEITSM', 'AMEXBK', 'AMEXBP', 'AMEXBT', 'AMEXEP', 'AMEXIN', 'AMEXSR',
    'AXPOPS', 'AXPVPN', 'EXCLCK', 'MIAMEX', 'MYAMEX',
  ],
  'Amreli Nagarik Sahkari Bank': ['ANSBNK'],
  'Andhra Bank': ['ANDBNK'],
  'Andhra Pradesh Grameena Vikas Bank': ['APGVBK'],
  'Andhra Pragathi Grameena Bank': [
    'APGBBK', 'APGBHO', 'APGBIT', 'APGBNK', 'APGECM', 'APHOAT', 'HORRMD',
    'ROATPM', 'ROKDPA', 'ROKDRI', 'ROKRNL', 'RONDYL', 'RONELR', 'ROONGL',
    'RORJPA',
  ],
  'Apna Sahakari Bank': ['APNABK', 'APNAPR', 'APNATR'],
  'Arihant Co-operative Bank': ['ACBLHO'],
  'Arunachal Pradesh Co-operative Apex Bank': ['APXBNK'],
  'Arunachal Pradesh Rural Bank': ['APRBBK', 'APRBHO'],
  'Associate Co-operative Bank': ['ASCBNK', 'ASSBNK', 'ASSOBK'],
  'Axis Bank': [
    'AXISB', 'AXISBK', 'AXISHR', 'AXISIN', 'AXISMR', 'AXISPR', 'AXISSR',
    'AXSFI', 'AXSFIN', 'FCHRGE', 'LICCRD', 'SMGPAY',
  ],
  'Bajiraoappa Sahakari Bank Ankalkhop': ['BASBNK'],
  'Balasinor Nagarik Sahakari Bank': ['BNSBL'],
  'Balotra Urban Co-operative Bank': ['BUCBKL', 'BUCBRJ'],
  'Bandhan Bank': ['154321', 'BDNSMS', 'BNDNBK', 'BNDNHL'],
  'Bank of Baroda': [
    'BOBBIZ', 'BOBBNK', 'BOBCMS', 'BOBCRM', 'BOBFRM', 'BOBMSG', 'BOBOTP',
    'BOBRAJ', 'BOBSCE', 'BOBSCF', 'BOBSMS', 'BOBTRE', 'BOBTXN', 'BOBUPG',
    'BOBUPI',
  ],
  'Bank of India': [
    '126995', 'BOIBAL', 'BOIIND', 'BOIINT', 'BOIJGB', 'BOILON', 'BOINJG',
    'BOIREM', 'BOISAF', 'BOISME', 'BOIVKG',
  ],
  'Bank of Maharashtra': ['MAHABK'],
  'Bank of Maharashtra Sc St & Obc Employees Association Pune': ['BOMSCT'],
  'Bankit Services': ['BANKIT'],
  'Baroda Rajasthan Kshetriya Gramin Bank': [
    'BRKGBD', 'BRKGBM', 'BRKGBS', 'BRKGBX',
  ],
  'Baroda U P Bank': ['BUPGBB', 'BUPGBM', 'BUPGBX'],
  'Basoda Nagrik Sahkari Bank': ['BASODA'],
  'Beawar Urban Co-operative Bank': ['BWRUCB'],
  'Belagavi District Central Co-operative Bank Belagavi': ['BDCCBK'],
  'Bhagini Nivedita Sahakari Bank Pune': ['BHAGNI', 'BHGINI', 'BNSBKL'],
  'Bhilwara Urban Co-operative Bank': ['BHUBNK', 'BURBAN'],
  'Bramhapuri Urban Co-operative Bank': ['BRAMHA', 'BUCBLB'],
  'CSB Bank': ['CSBBNK'],
  'Canara Bank': ['110111', 'CAANBK', 'CANBNK', 'CANRRB', 'CANRWD'],
  'Canara Bank Securities': ['CANMNY', 'CBSLTD'],
  'Canara Hsbc Oriental Bank of Commerce Life Insurance Company': [
    '111540', 'CHOINS',
  ],
  'Capital Small Finance Bank': ['CSFBNK'],
  'Central Bank of India': ['CBIOTP', 'CENTBK'],
  'Chaitanya Godavari Grameena Bank': ['CGGBNK'],
  'Chamoli Zila Sahkari Bank': ['CHADCC', 'CHAMBK'],
  'Chartered Sahakari Bank Niyamitha': ['CSBANK', 'CSBN', 'CSBNKN'],
  'Chennai Central Co-operative Bank': ['CCBANK'],
  'Chevayur Service Co-operative Bank': ['CHVRBK'],
  'Chhattisgarh Rajya Gramin Bank': ['CGBBBK', 'CRGBAD'],
  'Chhattisgarh State Co-operative Bank': ['CGAPBK'],
  'Chombal Service Co-operative Bank': ['CHSCBK'],
  'Chorode Service Co-operative Bank': ['CSCBNK'],
  'Citibank': ['152484', 'CITI', 'CITIBA', 'CITIBK', 'CITIBN'],
  'Citizens Co-operative Bank': ['CCOBNK', 'CTZENS'],
  'Citizens Urban Co-operative Bank': ['172586', 'CUCBNK'],
  'City Union Bank': [
    '111904', 'CUBANK', 'CUBFST', 'CUBLTD', 'CUBOTP', 'CUBSMS', 'CUBUPI',
  ],
  'Coastal Local Area Bank': ['CLABBK', 'COSTAL'],
  'Col Rd Nikam Sainik Sahakari Bank': ['SAINIK'],
  'Commercial Co-operative Bank': ['COMCBL'],
  'Contai Co-operative Bank': ['CCBLTD'],
  'Corporation Bank': ['CORPBK'],
  'D C C Bank': ['DGLCBK'],
  'DBS Bank': ['DBSBNK'],
  'DCB Bank': [
    '130000', '130012', '143242', '150000', '188888', '190000', '199199',
    'DCBANK', 'DCBBNK', 'DCBDCB',
  ],
  'Dakshin Bihar Gramin Bank': ['DGBSMS', 'MGBSMS'],
  'Dattatrya Maharaj Kalambejaoli Sahakari Bank': ['JAOLIB'],
  'Dausa Urban Co-operative Bank': ['DUCBDA'],
  'Deendayal Nagari Sahakari Bank Ambajogai': ['DEEBNK', 'DEENBK', 'DNSBNK'],
  'Dena Bank': ['BKDENA', 'DENABK', 'DGGBNK'],
  'Deogiri Nagari Sahakari Bank Aurangabad': ['DEOBNK'],
  'Deutsche Bank Ag': ['DBALRT', 'DEUTBK'],
  'Devika Urban Co-operative Bank': ['DUCOBK'],
  'Dhanlaxmi Bank': ['113000', 'DHANBK'],
  'Dharmapuri DCC Bank': ['DDCCBK'],
  'Dharmavir Sambhaji Urban Co-operative Bank': ['DSBANK', 'DSUCBK'],
  'Dhule and Nandurbar District Central Co-operative Bank': ['TDANCB'],
  'District Co-operative Bank Dehradun': ['DUNDCB'],
  'Doha Bank Qpsc India Branches': ['DOHABK'],
  'Dombivli Nagri Sahakari Bank': ['151234', 'DOMBNK'],
  'Dr Annasaheb Chougule Urban Co-operative Bank': ['DACBNK'],
  'Dr Appasaheb Urf Sa Re Patil Jaysingpurudgaon Sah Bank': [
    'AJUSBJ', 'JUSBNK',
  ],
  'Dwarkadas Mantri Nagkri Sahakari Bank Beed': ['DMNSBK'],
  'ESAF Small Finance Bank': [
    'EASFBT', 'ESAFIT', 'ESAFOT', 'ESAFPB', 'ESAFPR', 'ESAFSF', 'ESAFTR',
    'ESFUAT',
  ],
  'Ellaquai Dehati Bank': ['101979', 'EDBANK'],
  'Equitas Small Finance Bank': [
    '115551', '155551', 'EQBANK', 'EQUTAS', 'EQUTAT', 'EQUTAX',
  ],
  'Export Import Bank of India': ['EXIMBK'],
  'Fedbank Financial Services': ['FDBOTP', 'FEDFIN'],
  'Federal Bank': ['181818', 'FEDADV', 'FEDBNK', 'FEDOTP'],
  'Fincare Small Finance Bank': ['107750', 'FNCARE'],
  'Fingrowth Co-operative Bank': ['FGUCBK', 'FNGWBK'],
  'Fino Payments Bank': ['FINOBK', 'FINOHR', 'FINOIN', 'FINOPB'],
  'Gautam Sahakari Bank': ['GSBANK'],
  'Ghoghamba Vibhag Naglik Sahakari Bank': ['GVNSBL'],
  'Gondal Nagrik Sahakari Bank': ['GNSBKL'],
  'Gondia Dist Central Co-operative Bank': ['106486', '159159', 'GNDDCC'],
  'Gopinath Patil Parsik Janata Sahakari Bank': [
    '151892', '192518', 'GPPJSB', 'GPPSBL',
  ],
  'Guardian Souharda Sahakari Bank Niyamita': ['GSSBNK'],
  'Gujarat Ambuja Co-operative Bank': ['AMBUJA', 'GUJAMB'],
  'Gulshan Mercantile Urban Co-operative Bank': ['GCBBNK'],
  'H P State Co-operative Bank': ['HPSBNK'],
  'HDFC Bank': [
    '146587', 'DPCSDX', 'EBTALT', 'HDFCAL', 'HDFCBA', 'HDFCBK', 'HDFCBN',
    'HDFCCC', 'HDFCDC', 'HDFCFD', 'HDFCGC', 'HDFCHI', 'HDFCHL', 'HDFCIT',
    'HDFCLI', 'HDFCPL', 'HDFCRD', 'HDFCSD', 'HDFCSE', 'HDFCUN', 'HDFSET',
    'HDFTST', 'HRHDFC', 'MIMTMX', 'PAYZAP', 'UNIXCE',
  ],
  'HSBC': ['100022', 'HSBCBK', 'HSBCEX', 'HSBCIM', 'HSBCIN'],
  'Hamirpur District Co-operative Bank': ['HDCCBK'],
  'Himachal Pradesh Gramin Bank': ['HPGSMS'],
  'Himatnagar Nagrik Sahakari Bank': ['HNSBNK'],
  'Hutatma Sahakari Bank Walwa': ['HSBANK', 'HSBLBK', 'HSBNKW'],
  'ICICI Bank': [
    '142421', '142424', 'ICBANK', 'ICIBNK', 'ICICBK', 'ICICIB', 'ICICIH',
    'ICICIK', 'ICICIL', 'ICICTC', 'ICIEMP', 'ICIOTP', 'ISECLD', 'ISRVCE',
  ],
  'IDBI Bank': ['111444', 'IDBIBK', 'IDBIDL'],
  'IDFC FIRST Bank': [
    '111101', '111102', '111103', '111104', '111105', '111106', '111107',
    '111108', '111109', 'IDFCBK', 'IDFCCM', 'IDFCFB', 'IDFCFZ', 'IDFCIT',
    'IDFCTS', 'IDFCZ', 'IDFSIT',
  ],
  'India Post Payments Bank': [
    'IPBCOM', 'IPBKYC', 'IPBMSG', 'IPBOFR', 'IPBOTP', 'IPBSEC', 'MYIPPB',
  ],
  'Indian Bank': ['INBUPI', 'INDBNK'],
  'Indian Overseas Bank': [
    'IOBANK', 'IOBATM', 'IOBBNK', 'IOBBQR', 'IOBCHN', 'IOBHRD', 'IOBJLS',
    'IOBMKT', 'IOBOTP',
  ],
  'Indira Mahila Sahakari Bank': ['IMSBNK'],
  'Indore Paraspar Sahakari Bank': ['116077', 'IPSBNK', 'IPSHOI', 'IPSHOT'],
  'Indore Premier Co-operative Bank': ['IPCBBK', 'IPCBNK'],
  'Indraprastha Sehkari Bank': ['ISBANK'],
  'IndusInd Bank': ['126666', '127777', 'INDUSA', 'INDUSB', 'INDUSO'],
  'Integral Urban Co-operative Bank': ['INTBNK'],
  'Irinjalakuda Town Co-operative Bank': ['ITCBBK', 'ITCBNK'],
  'J&K Bank': ['133333', 'JKBANK', 'JKCARD'],
  'J&k Grameen Bank': ['GRAMEN', 'JGRAMN', 'JKGRAM', 'JKGRMN', 'JKGRNB'],
  'JK Bank Financial Services': ['JKBFSL'],
  'Jaiprakash Narayan Nagri Sahakari Bank': ['JPNBNK'],
  'Jalaun District Coopertive Bank Orai': ['JALAUN'],
  'Jalgaon Janata Sahkari Bank Jalgaon': ['111979', 'JJSBNK'],
  'Jalna Merchants Co-operative Bank Jalna': ['JMCBNK'],
  'Jalore Nagrik Sahakari Bank': ['JALORE', 'JLRNSB'],
  'Jana Small Finance Bank': ['JANABK', 'JANATR', 'JANATX'],
  'Janakalyan Sahakari Bank': ['151974', 'JKSBLM'],
  'Janaseva Co-operative Bank Nashik': ['JNJCBL'],
  'Janaseva Sahakari Bank Borivli': ['JNSEVA'],
  'Janaseva Sahakari Bank Hadapsar Pune': ['JANSVA'],
  'Janata Sahakari Bank Amravati': ['JSBLBK'],
  'Janata Sahakari Bank Gondia': ['JSBGON', 'JSBLHO'],
  'Janata Sahakari Bank Kurduwadi': ['JSBANK'],
  'Janata Sahakari Bank Pune': ['JSBLPN'],
  'Janatha Seva Co-operative Bank': ['JANTHA', 'JSCBKL'],
  'Jankalyan Urban Co-operative Bank Kallam': ['JUCBNK'],
  'Jhalawar Nagrik Sahakari Bank': ['JNSBBM', 'TJNSBK'],
  'Jharkhand Rajya Gramin Bank': ['142019', 'JRGBNK'],
  'Jijamata Mahila Sahakari Bank': ['JMSBLP', 'JMSBNK'],
  'Jila Sahakari Kendriya Bank Durg': ['DURGBK'],
  'Jila Sahakari Kendriya Bank Maryadit Ambikapur': ['JSKABK'],
  'Jila Sahakari Kendriya Bank Maryadit Balaghat': ['JSKBBG'],
  'Jila Sahakari Kendriya Bank Maryadit Betul': ['CCBBTL'],
  'Jila Sahakari Kendriya Bank Maryadit Chhatarpur': ['JSKBCP'],
  'Jila Sahakari Kendriya Bank Maryadit Damoh': ['JSKBDA'],
  'Jila Sahakari Kendriya Bank Maryadit Datia': ['CCBDTA'],
  'Jila Sahakari Kendriya Bank Maryadit Dewas': ['CCBDWS'],
  'Jila Sahakari Kendriya Bank Maryadit Dhar': ['DHARBK', 'DHARCB'],
  'Jila Sahakari Kendriya Bank Maryadit Guna': ['CBGUNA'],
  'Jila Sahakari Kendriya Bank Maryadit Gwalior': ['CCBGWL'],
  'Jila Sahakari Kendriya Bank Maryadit Jabalpur': ['JSKBJP'],
  'Jila Sahakari Kendriya Bank Maryadit Jagdalpur': ['JSKJBK'],
  'Jila Sahakari Kendriya Bank Maryadit Khandwa': ['CCBKNW'],
  'Jila Sahakari Kendriya Bank Maryadit Mandla': ['DCBMDL'],
  'Jila Sahakari Kendriya Bank Maryadit Mandsaur': ['JSKBMS'],
  'Jila Sahakari Kendriya Bank Maryadit Raisen': ['JSKBRS'],
  'Jila Sahakari Kendriya Bank Maryadit Rajnandgaon': ['JSKBBK'],
  'Jila Sahakari Kendriya Bank Maryadit Ratlam': ['JSKBRT'],
  'Jila Sahakari Kendriya Bank Maryadit Rewa': ['CBREWA'],
  'Jila Sahakari Kendriya Bank Maryadit Satna': ['CCBSTN'],
  'Jila Sahakari Kendriya Bank Maryadit Sehore': ['CCBSHR'],
  'Jila Sahakari Kendriya Bank Maryadit Seoni': ['CCBSNI'],
  'Jila Sahakari Kendriya Bank Maryadit Shajapur': ['JSKBSJ'],
  'Jila Sahakari Kendriya Bank Maryadit Sidhi': ['CCBSDH'],
  'Jila Sahakari Kendriya Bank Maryadit Tikamgarh': ['CCBTKG'],
  'Jila Sahakari Kendriya Bank Maryadit Ujjain': ['JSKBUJ'],
  'Jila Sahakari Kendriya Maryadit Bank Chhindwara': ['CCBCHW', 'CHHIBK'],
  'Jila Sahakari Kendriya Maryadit Bank Hoshangabad': ['JSKBHB'],
  'Jila Sahakari Kendriya Maryadit Bank Khargone': ['CCBKGN'],
  'Jila Sahakari Kendriya Maryadit Bank Morena': ['CCBMOR'],
  'Jila Sahakari Kendriya Maryadit Bank Sagar': ['CCBSGR'],
  'Jila Sahakari Kendriya Maryadit Bank Vidisha': ['JSKBVI', 'VIDBBK'],
  'Jila Sahakari Kendriya Marydit Bank Jhahua': ['JSKBJH'],
  'Jila Sahakari Kenriya Maryadit Bank Narsinghpur': ['JSKBNP'],
  'Jila Saharkari Kendriya Maryadit Bank Rajgarh': ['CCBRJG'],
  'Jila Sahkari Kendriya Maryadit Bank Raipur': ['JSBRYP'],
  'Jila Shahkari Kendriya Bank Maryadit Shivpuri': ['CCBSVP'],
  'Jilasahakari Kendriya Bank Maryadit Shahdol': ['JSKBSD'],
  'Jivaji Sahakari Bank Ichalkaranji': ['JIVAJI'],
  'Jivan Commercial Co-operative Bank': ['JCCBNK', 'JCOMBK'],
  'Jodhpur Nagrik Sahkari Bank': ['JNSBJU', 'JNSBKL'],
  'Jogindra Central Co-operative Bank Solan': ['JCCB'],
  'Kakkattil Co-operative Rural Bank': ['KCRBNK'],
  'Kallappanna Awade Ichalkaranji Janata Sahakari Bank Ichalkaranji': [
    'KAIJSB',
  ],
  'Kancheepuram Central Co-operative Bank': ['KPMCCB'],
  'Kankaria Maninagar Nagrik Sahakari Bank': ['KMNBNK'],
  'Karnataka Bank': [
    '128119', '150773', '180224', 'KARBNK', 'KBLBNK', 'KRNBNK', 'KRTBNK',
    'KTKBNK',
  ],
  'Karnataka Gramin Bank': ['111611', '114411', '116611', '20001', 'KAGBNK'],
  'Karnataka Vikas Grameena Bank': ['KVGBBK', 'KVGBNK', 'KVGECM'],
  'Karur Vysya Bank': ['191600', '191607', 'KVBANK', 'KVBOTP', 'KVBUPI'],
  'Kashipur Urban Co-operative Bank': ['KUCBBK'],
  'Kedarnath Urban Co-operative Bank': ['KUBANK'],
  'Kerala Gramin Bank': ['113311', 'KGBANK'],
  'Kohinoor Sahakari Bank Ichalkaranji': ['KSBLBK'],
  'Kokan Mercantile Co-operative Bank': ['100075', 'KMCBK'],
  'Kolhapur District Central Co-operative Bank': ['KDCCBL'],
  'Kota Nagrik Sahkari Bank': ['KOTABK', 'MDKNSB'],
  'Kotak Mahindra Bank': [
    '100811', '111000', '111888', '189766', 'KBANKT', 'KOTAKB', 'KOTAKP',
    'KTKREM',
  ],
  'Koteshwarasahakaribankniyamitha': ['KOTSBN'],
  'Koyana Sahakari Bank Karad': ['KOYANA'],
  'Krishiseva Urban Co-operative Bank': ['KRUSHI'],
  'Krishna Bhima Samrudhi Local Area Bank': ['KBSBBK', 'KBSBNK'],
  'Krishna Mercantile Co-operative Bank Bhopal': ['KMCBLT'],
  'Kurmanchal Nagar Sahkari Bank': ['118467', 'KNSBKN', 'KUNSBB', 'KUNSUB'],
  'Lakhimpur Urban Co-operative Bank': ['LMPUCB'],
  'Lala Urban Bank': ['LALABK'],
  'M P Rajya Sahakari Bank Mydt Bhopal': ['MPAPEX', 'MPRSBK'],
  'Mahanagr Nagrik Sahakari Bank Mydt Bairas': ['MNBANK'],
  'Maharashtra Gramin Bank': ['MGBBNK'],
  'Mahatma Fule Urban Co-operative Bank Amravati': ['MFDUBK'],
  'Mahaveer Co-operative Urban Bank': ['180797', 'MCUBLH'],
  'Mahesana District Co-operative Bank': ['MDCBKL', 'MDCBNK'],
  'Mahesh Sahakari Bank Pune': ['MSBLPN'],
  'Mahesh Urban Co-operative Bank Parbhani': ['MUCBLP'],
  'Mahesh Urban Coperative Bank': ['MUCBNP'],
  'Mahila Co-operative Nagrik Bank': ['MCNBBK'],
  'Makarpura Industrial Estate Co-operative Bank': ['MAKBNK', 'MIECBL'],
  'Mamasaheb Pawar Satyavijay Co-operative Bank': ['MPSCBK'],
  'Maninagar Co-operative Bank': ['MCOBNK'],
  'Manjeri Co-operative Urban Bank': ['MCUBNK'],
  'Mann Deshi Mahila Sahakari Bank Mhaswad': ['MDMSBK', 'MMSBNK'],
  'Mansarovar Urban Co-operative Bank': ['MANSBK'],
  'Mansing Co-operative Bank Dudhondi': [
    'MCBATM', 'MCBLTD', 'MCBOTP', 'MCBTRN',
  ],
  'Manvi Pattana Souharrda Sahakari Bank Niyamita': ['MPSSBK', 'MPSSBN'],
  'Maruthonkara Service Co-operative Bank': ['MARSCB'],
  'Meghalaya Rural Bank': ['MEGRRB', 'MGRBBK', 'MRBBBK'],
  'Mizoram Rural Bank': ['MZBANK', 'MZBBBK'],
  'Moodadi Service Co-operative Bank': ['MSCBNK'],
  'Moolathara Service Co-operative Bank': ['MLTBNK'],
  'Moradabad Zila Sahkari Bank': ['DCBMBD', 'MORADA'],
  'Mudgal Urban Co-operative Bank Mudgal': ['158412', 'MDLUCB', 'MUBANK'],
  'Muzaffarnagar District Co-operative Bank': [
    'BRIMPS', 'CDSAFE', 'ECOMPW', 'MBIMPS', 'UPIPWD',
  ],
  'NSDL Payments Bank': ['111555', 'NSDLCD', 'NSDLPB', 'NSDLRM'],
  'Nadapuram Service Co-operative Bank': ['NSCBAK'],
  'Nagar Sahakari Bank Etawah': ['NSBETW'],
  'Nagar Vikas Sahakari Bank': ['NVSHUP'],
  'Nandani Sahkari Bank Nandani': ['NSBANK', 'NSBNKN'],
  'National Bank for Agriculture and Rural Development': ['NABARD'],
  'Nav Jeevan Co-operative Bank': ['140285', 'TNJCBL'],
  'Navsarjan Industrial Co-operative Bank': ['NICBNK'],
  'Nidhi Co-operative Bank': ['NCBLBK'],
  'Nishigandha Sahakari Bank': ['NISBNK'],
  'Nutan Nagarik Sahakari Bank': ['NUTANB'],
  'Onchiyam Service Co-operative Bank': ['OSCBNK'],
  'Oriental Bank of Commerce': [
    '140601', 'OBCBNK', 'OBCCBS', 'OBCINB', 'OBCMBK', 'OBCOLS', 'OBCOTP',
    'OBCSMS', 'OBCSVC', 'OBCTXN', 'OBCUPI',
  ],
  'Padra Nagar Nagrik Sahakari Bank': ['PNNSBL'],
  'Pali Urban Co-operative Bank': ['PUBANK', 'PUCBNK'],
  'Palus Sahakari Bank': ['PALUSB'],
  'Paschim Banga Gramin Bank': ['PBGBBN', 'PBGKOL', 'PBGMPB'],
  'Patan Nagarik Sahakari Bank': ['PATANB', 'PNSBNK'],
  'Pattanchery Service Co-operative Bank': ['PATSCB'],
  'Pattom Service Co-operative Bank': ['PSCBNK'],
  'Paytm Payments Bank': ['PAYTMB'],
  'Peoples Co Opperative Bank Dholka': ['PCBDLK'],
  'Perumatty Service Co-operative Bank': ['PMTYBK'],
  'Pithoragarh Zila Sahkari Bank Pithoragarh': ['PITDCC', 'PITOBK'],
  'Pochampally Co-operative Urban Bank': ['PCUBNK', 'POUCBK'],
  'Ponmeri Service Co-operative Bank': ['PMRYBK'],
  'Poornawadi Nagrik Sahakari Bank Maryadit Beed': ['BKPNSB', 'PNSBKB'],
  'Porbandar Commercial Co-operative Bank': ['PCCBNK'],
  'Pragati Mahila Nagrik Sahakari Bank Maryadit': ['PMNSBM'],
  'Pragati Sahakari Bank': ['PSBLTD'],
  'Prathama U P Gramin Bank': ['PUPGBK'],
  'Prime Co-operative Bank': ['PCOBNK', 'PRIMEB'],
  'Priyadarshani Urban Co-operative Bank': ['PRYBNK'],
  'Priyadarshni Nagari Sahakari Bank Jalna': ['PRIBNK'],
  'Pune Cantonment Sahakari Bank': ['PCSBNK'],
  'Pune Peoples Co-operative Bank Pune': ['PPCBNK'],
  'Punjab & Sind Bank': ['PSBANK'],
  'Punjab Gramin Bank': ['PGBSMS', 'PNBACS'],
  'Punjab National Bank': [
    'PNBCCD', 'PNBCRD', 'PNBCRM', 'PNBDBD', 'PNBHRD', 'PNBJNK', 'PNBLKO',
    'PNBMKT', 'PNBOTP', 'PNBRTS', 'PNBSMS', 'PNBTBD',
  ],
  'Punjab and Maharashtra Co-operative Bank': ['130013', 'PMCBNK'],
  'Purvanchal Bank': ['PURBNK'],
  'Pusad Urban Co-operative Bank': [
    'PUBBNK', 'PUBLTD', 'PUCBLL', 'PUCBLP', 'PUSBNK',
  ],
  'RBL Bank': [
    '120011', '121111', '121314', '130001', '130011', '131415', '140001',
    '140011', '150001', '160001', 'FASTDV', 'RATNAK', 'RBLBBB', 'RBLBNK',
    'RBLCCC', 'RBLCRD', 'RBLHRD', 'RBLINF', 'RBLKYC', 'RBLOFR', 'RBLOSR',
    'RBLPIL', 'RBLPLN', 'RBLSSU', 'RBLTEC', 'RBLVPN', 'RBLWCM', 'SPRCRD',
    'SPROFR',
  ],
  'Rackbank Datacenters': ['RACBNK'],
  'Rajapur Urban Co-operative Bank Rajapur': ['RAJABK', 'RUBANK'],
  'Rajarambapu Bank Sahakari Bank': ['123323', 'RSBLPT'],
  'Rajarshi Shahu Sahakari Bank': ['RSSBBK'],
  'Rajasthan Marudhara Gramin Bank': ['RMGBBK'],
  'Rajdhani Nagar Sahkari Bank': ['RNSBNK'],
  'Rajkot Nagarik Sahakari Bank': [
    '151053', 'RNBASB', 'RNBCRM', 'RNBUPI', 'RNSBAL', 'RNSBBC', 'RNSBKT',
    'RNSBLD', 'RNSBLT', 'RNSBMB', 'RNSBMF',
  ],
  'Rajputana Mahila Urban Co-operative Bank': ['RMCBNK', 'TRMUCB'],
  'Rander Peoples Co-operative Bank': ['RPCOBL'],
  'Rani Channamma Mahila Sahakari Bank Niyamit Belagavi': ['BZRCMB', 'RCMSBN'],
  'Raniganj Co-operative Bank': ['RCBRNG', 'RCOBKL'],
  'Ravi Commercial Urban Co-operative Bank': ['RAVISC'],
  'Reserve Bank of India': ['CMSRBI', 'RBISAY'],
  'Rukmini Sahakari Bank': ['RUKBNK'],
  'SVC Co-operative Bank': ['121906', 'SVCBNK', 'SVCINF', 'SVCTXN'],
  'Sadalga Urbansouharda Sahakari Bank Niyamit': ['SUSSBN'],
  'Sadhana Sahakari Bank': ['SADHNA', 'SSBNAG', 'SSBPUN'],
  'Sahakarmaharshi Bhausaheb Thorat Amrutvahini Sahakari Bank': ['SBTABK'],
  'Saibaba Nagari Sahakari Bank Maryadit Sailu': ['SAIBNK', 'SNSBMS'],
  'Samaja Seva Sahakari Bank': ['SSBNBL'],
  'Samarth Sahakari Bank Maryadit Jalna': ['SSBMJA'],
  'Samarth Sahakari Bank Solapur': ['SBLSOL'],
  'Samata Sahakari Bank': ['SAMBNK'],
  'Sampada Sahakari Bank': ['SAMSAH', 'SSBKLP'],
  'Samruddhi Co-operative Bank Nagpur': ['132132'],
  'Sandur Pattana Souharda Sahakari Bank Ni': ['SANDUR'],
  'Sanmati Sahakari Bank Ichalkaranji': ['SANMTI'],
  'Sanmitra Mahila Nagri Sahkari Bank Maryadit Chandrapur': ['SMSBNK'],
  'Saraspur Nagrik Co-operative Bank': ['SNCOBL'],
  'Sardar Singh Nagrik Sahkari Bank Maryadit Tikamgarh': ['SSNSBK', 'SSNSBM'],
  'Sardar Vallabhbhai Sahakari Bank': ['SVBANK'],
  'Sardargunj Mercantile Co-operative Bank': ['SMCBNK'],
  'Sarva Haryana Gramin Bank': ['SHGSMS'],
  'Sarvodaya Nagarik Sahakari Bank': ['SARNSB', 'SNBHMT'],
  'Saurashtra Gramin Bank': ['SGBBNK', 'SGBBTI', 'SRGBBK'],
  'Sawaimadhopur Urban Co-operative Bank': ['SWMUCB'],
  'Sberbank': ['SBERIN'],
  'Sbm Bank India': ['SBMBNK', 'SBMIND'],
  'Shankarrao Mohite Patil Sahakari Bank Akluj': ['SMPBNK'],
  'Sharad Nagari Sahakari Bank Solapur': ['SNSBLS'],
  'Sharad Sahakari Bank Manchar Pune': ['SSBANK', 'SSBMAN'],
  'Shillong Co-operative Urban Bank': ['SCUBLT'],
  'Shinhan Bank': ['SHBIND'],
  'Shivalik Mercantile Co-operative Bank': ['SMCBLT'],
  'Shivdaulat Sahakari Bank': ['SHIVBK'],
  'Shree Bharat Co-operative Bank': ['SBHART'],
  'Shree Bhavnagar Nagrik Sahakari Bank': ['BNSBNK'],
  'Shree Chhani Nagrik Sahakari Bank': ['CNBANK'],
  'Shree Dharati Co-operative Bank': ['DHRTBK', 'SDCOBK'],
  'Shree Kadi Nagarik Sahakri Bank': ['KNBOTP', 'OTPSKN', 'SKNSBL'],
  'Shree Laxmi Mahila Sahakari Bank': ['SLMSBL'],
  'Shree Mahesh Co-operative Bank': ['MCBNSK'],
  'Shree Mahuva Nagrik Sahakari Bank': ['SMNBNK'],
  'Shree Panchganga Nagari Sahakari Bank Kolhapur': ['SPNSBK'],
  'Shree Parswanath Co-operative Bank': ['PCBANK'],
  'Shree Savarkundla Nagarik Sahakari Bank': ['SKNSBK'],
  'Shree Savli Nagrik Sahakari Bank': ['SAVLIP'],
  'Shree Talaja Nagrik Sahakari Bank': ['STNSBL'],
  'Shree Vardhaman Sahkari Bank': ['VSBANK'],
  'Shri Adinath Co-operative Bank Ichalkaranji': ['ADINBK', 'SACBNK'],
  'Shri Basaveshwar Sahakari Bank Niyamit Bagalkot': ['BASAVA', 'BSBLTD'],
  'Shri Chatrapati Shivaji Maharaj Sahakari Bank Niyamith': ['SCSBNK'],
  'Shri Chhatrapati Rajarshi Shahu Urban Co-operative Bank Beed': ['SHAHUB'],
  'Shri Gajanan Maharaj Urban Co-operative Bank Bhokardan': ['SGMUCB'],
  'Shri Govardhansinghji Raghuvanshi Sah Bank': ['GRBANK'],
  'Shri Janata Sahakari Bank': ['JSBLHG', 'SHSBLH', 'SJSBLH'],
  'Shri Mahavir Urban Co-operative Bank': ['MHAVIR', 'SMUCBS'],
  'Shri Swami Samarth Sahakari Bank': ['SSSSBK'],
  'Shri Yashwant Sahakari Bank Maryadit Kuditre(kumbhi': ['YASHBK'],
  'Shrikrishna Co-operative Bank Umrer': ['SRKCOB'],
  'Shrimant Malojiraje Sahakari Bank': ['MALOJI', 'MSBLTD'],
  'Shriram Urban Co-operative Bank Nagpur': ['SUBANK', 'SUCNAG'],
  'Sihor Nagariksahakari Bank': ['SNSBNK'],
  'Sikkim State Co-operative Bank': ['SIKSBK'],
  'Small Industries Development Bank of India': ['SIDBIB'],
  'Sonbhadra Nagar Sahkari Bank': ['SONBNK'],
  'Soubhagya Mahila Souharda Sahakari Bank Niyamit': ['SMSSBK'],
  'South Indian Bank': ['SIBCNP', 'SIBPRD', 'SIBSMS'],
  'Sree Banashankari Mahila Co-operative Bank': ['180597', 'SBMCB', 'SBMCBK'],
  'Sreenidhi Souharda Sahakari Bank Niyamitha': ['SRIBNK', 'SSSBKN', 'SSSBNB'],
  'Sri Satya Sai Nagrik Sahakari Bank Maryadit': ['SSSBNK'],
  'Standard Chartered': ['FROMSC', 'SCBANK'],
  'State Bank of India': [
    '141516', 'ACEPLC', 'AGMITS', 'ATMMON', 'ATMMVS', 'ATMSBI', 'ATMSMS',
    'ATMTAD', 'CBSSBI', 'CCCDEL', 'CCHRIR', 'CCONLN', 'CCPCAH', 'CCPCCN',
    'CCRSBI', 'CFOBAN', 'CMPHYD', 'CSDSBI', 'CTDSBI', 'CTMUGM', 'CVELUC',
    'DBPSBI', 'DGTBNK', 'DUNICA', 'EDSADM', 'FIDSBI', 'FMCLUC', 'FSLOCT',
    'GCCSBI', 'GRCSBG', 'GRCSBI', 'GSCLOC', 'HRMSCC', 'IAPPRV', 'ICMTRG',
    'IMAHYD', 'ISDSBI', 'ITCOMP', 'ITRISK', 'ITRSNC', 'ITSDEL', 'ITSLHO',
    'KHLADM', 'LCTSCS', 'LHOABU', 'LHOBAN', 'LHOGMI', 'LHOKOL', 'LHOPAT',
    'MABHYD', 'MISDEP', 'PIMSBI', 'PPGDEP', 'PVIJAY', 'RBOPEN', 'RMMBNR',
    'RMRBLY', 'SAMLMS', 'SBBJNB', 'SBCDRE', 'SBCWMS', 'SBDBTL', 'SBDCOG',
    'SBECOM', 'SBEPAY', 'SBEREG', 'SBERMS', 'SBFIAH', 'SBFIMF', 'SBGALR',
    'SBGITC', 'SBGLMS', 'SBGMBS', 'SBGPPC', 'SBHIGH', 'SBHINB', 'SBHRMS',
    'SBIABD', 'SBIABU', 'SBIACS', 'SBIADS', 'SBIAHM', 'SBIAND', 'SBIAOR',
    'SBIAPP', 'SBIATM', 'SBIATT', 'SBIAVS', 'SBIBAN', 'SBIBHO', 'SBIBHU',
    'SBIBNK', 'SBIBOG', 'SBIBSC', 'SBIBTU', 'SBICAA', 'SBICAR', 'SBICBG',
    'SBICDC', 'SBICDS', 'SBICHA', 'SBICHD', 'SBICHE', 'SBICMD', 'SBICMP',
    'SBICMS', 'SBICON', 'SBICOS', 'SBICPA', 'SBICPC', 'SBICPP', 'SBICRS',
    'SBICVC', 'SBICVE', 'SBICVS', 'SBICWS', 'SBIDAK', 'SBIDBT', 'SBIDCL',
    'SBIDEL', 'SBIDGT', 'SBIDIA', 'SBIDMO', 'SBIDMT', 'SBIDRC', 'SBIDRT',
    'SBIDSB', 'SBIDTB', 'SBIDYN', 'SBIEES', 'SBIEIS', 'SBIEMM', 'SBIEST',
    'SBIETC', 'SBIETF', 'SBIETM', 'SBIEWS', 'SBIFIJ', 'SBIFMC', 'SBIFMS',
    'SBIFOB', 'SBIFRW', 'SBIFXT', 'SBIGAD', 'SBIGCC', 'SBIGKP', 'SBIGLM',
    'SBIGLS', 'SBIGMU', 'SBIGOC', 'SBIGRC', 'SBIGUW', 'SBIHOM', 'SBIHRD',
    'SBIHSG', 'SBIHUB', 'SBIHYD', 'SBIINB', 'SBIINF', 'SBIITS', 'SBIIVM',
    'SBIJAI', 'SBIKBN', 'SBIKBP', 'SBIKER', 'SBIKOL', 'SBIKYC', 'SBILCM',
    'SBILCO', 'SBILKL', 'SBILON', 'SBILOS', 'SBILOT', 'SBILTP', 'SBILUC',
    'SBILWF', 'SBIMAB', 'SBIMAH', 'SBIMAP', 'SBIMAT', 'SBIMBD', 'SBIMBS',
    'SBIMET', 'SBIMFK', 'SBIMUM', 'SBINPA', 'SBINPS', 'SBINTH', 'SBINWC',
    'SBINWD', 'SBINZB', 'SBIOEM', 'SBIONB', 'SBIOTP', 'SBIOTS', 'SBIPAY',
    'SBIPBS', 'SBIPBU', 'SBIPEN', 'SBIPER', 'SBIPNJ', 'SBIPOS', 'SBIPPC',
    'SBIPRM', 'SBIPSG', 'SBIPSP', 'SBIQCK', 'SBIRBH', 'SBIRBU', 'SBIRCH',
    'SBIRDH', 'SBIREG', 'SBIREH', 'SBIRMD', 'SBIRPR', 'SBIRTI', 'SBIRWZ',
    'SBISAM', 'SBISBD', 'SBISEC', 'SBISFG', 'SBISMA', 'SBISMB', 'SBISMC',
    'SBISME', 'SBISMP', 'SBISNB', 'SBISNC', 'SBISNP', 'SBISOC', 'SBISOM',
    'SBISRP', 'SBITBU', 'SBITDS', 'SBITFF', 'SBITFO', 'SBITRB', 'SBITRI',
    'SBITRN', 'SBITRS', 'SBITSM', 'SBITSS', 'SBITST', 'SBIUDR', 'SBIUPI',
    'SBIVMT', 'SBIVPN', 'SBIWAL', 'SBIWEB', 'SBJSMS', 'SBLCPC', 'SBLLMS',
    'SBLSPC', 'SBMCSH', 'SBMINB', 'SBOCAS', 'SBPBBU', 'SBPINB', 'SBRACC',
    'SBRLMS', 'SBRWDZ', 'SBSSBI', 'SBTINB', 'SBWLTH', 'SBYONO', 'SOCINC',
    'SSCORE', 'SSKSBH', 'SSKSBI', 'SSKSBM', 'SSKSBP', 'SSKSBT', 'WMBSMS',
  ],
  'Stella Maris School of Banking': ['STELLA'],
  'Suco Souhardha Sahakari Bank': ['SUCOBK'],
  'Sulaimani Co-operative Bank': ['SULBNK'],
  'Sumerpur Mercantile Urban Co-operative Bank': ['SMUCBK', 'SMUCBL'],
  'Surat National Co-operative Bank': ['SUNBNK', 'SURATB'],
  'Suryoday Small Finance Bank': [
    '120017', 'SMFLTD', 'SRYLTD', 'SSBFNK', 'SSFBNK',
  ],
  'Syndicate Bank': [
    'ASBALT', 'BPMCTR', 'BRDSEC', 'CIRALT', 'COVIGL', 'DGMGZB', 'DGMGZD',
    'DGMRBD', 'DITATM', 'DITHLP', 'DMSALT', 'EMLOTP', 'FGMCHN', 'FGMMUM',
    'GMCCDC', 'GMPERS', 'GMSMAD', 'HOCPPC', 'HOHRMS', 'HOSRDD', 'LDMFBD',
    'MBTEST', 'NPCMPL', 'RIMUMB', 'ROLUDH', 'RONELL', 'RORURL', 'ROTVPM',
    'ROUDPI', 'ROVARN', 'SBALRT', 'STCBLR', 'SUPRNA', 'SWDEPT', 'SYBGOV',
    'SYBKDC', 'SYDBTL', 'SYNBNK', 'SYNBPR', 'SYNDBK', 'SYNDBT', 'SYNDCT',
    'SYNDLN', 'SYNDPG', 'SYNEPB', 'SYNIBD', 'SYNINS', 'SYNKSD', 'SYNMOB',
    'SYNRBD', 'SYNRUP', 'SYNTAB', 'SYNTST', 'SYNVIG', 'TDCELL', 'THIRUV',
  ],
  'TJSB Sahakari Bank': ['TJSBIB', 'TJSBNK', 'TJSBPM', 'TJSBSB', 'TJSBVV'],
  'Tamilnad Mercantile Bank': [
    '111921', 'TMBANK', 'TMBFST', 'TMBOTP', 'TMBSMS', 'TMBUPI',
  ],
  'Tarapur Co-operative Urban Bank': ['TCUBNK'],
  'Tehri Garhwal Zila Sahkari Bank': ['TEHBIK', 'TGDCBT'],
  'Telangana Grameena Bank': [
    'CBSTGB', 'DCGBBK', 'TGBATM', 'TGBBNK', 'TGBEBK', 'TGBINB', 'TGBMBS',
    'TGBTXN', 'TGBUPI',
  ],
  'Textile Traders Co-operative Bank': ['TTCOBK'],
  'Tgmc Bank': ['TGMCBK'],
  'Tha Mahila Vikas Co-operative Bank': ['MVCBLS'],
  'Thane Bharat Sahakari Bank': ['TBSBNK'],
  'The Adarsh Co-operative Urban Bank': ['199802', 'ADARSH', 'ADHBNK'],
  'The Adilabad District Co-operative Central Bank Adilabad': ['ADBCCB'],
  'The Ahmedabad Mercantile Co-operative Bank': ['AMCBNK', 'AMCOBK'],
  'The Akola Urban Co-operative Bank': ['AKOLAB', 'AUCBNK'],
  'The Alwaye Urban Co-operative Bank': ['ALYBNK'],
  'The Amod Nagric Co-operative Bank': ['TANCBL'],
  'The Amravati Zillha Parishad Shikshak Sahkari Bank Amravati': [
    'AZPSSB', 'ZPSBNK',
  ],
  'The Anantapur District Co-operative Central Bank': ['ATPCCB'],
  'The Anantnag Central Co-operative Bank': ['ACCBNK'],
  'The Andhra Pradesh State Co-operative Bank': ['APSCOB'],
  'The Annasaheb Savant Co-operative Urban Bank Mahad': ['ASBANK'],
  'The Badagara Co-operative Rural Bank': ['BCRBNK'],
  'The Baghat Urban Co-operative Bank': ['BUCBBK'],
  'The Balussery Co-operative Urban Bank': ['BCUBNK'],
  'The Banaskantha Mercantile Co-operative Bank': ['BMCBBK', 'BMCBNK'],
  'The Baramati Sahakari Bank': ['BSBBMT', 'BSBLBK'],
  'The Baroda Traders Co-operative Bank': ['TBTCOB'],
  'The Becharaji Nagarik Sahakari Bank': ['TBNSBL'],
  'The Begusarai Central Cooprative Bank': ['BEGUBK'],
  'The Bhabhar Vibhag Nagrik Sahakari Bank': ['BHABHR'],
  'The Bhagyalakshmi Mahila Sahakari Bank Nanded': ['BMSHAB', 'BMSNAN'],
  'The Bhagyodaya Co-operative Bank': ['BCOBBK', 'TBCBKL'],
  'The Bhandara Urban Co-operative Bank': ['BUCBNK'],
  'The Bharat Co-operative Bank': ['BNKBCB', 'TBCOOP'],
  'The Bhuj Commercial Co-operative Bank': ['BCCBBK', 'BHUJBK'],
  'The Bihar State Co-operative Bank': ['BHRDBK', 'BSCBNK'],
  'The Bijnor Urban Co-operative Bank': ['TBUCBK'],
  'The Chanasma Nagrik Sahakari Bank': ['CNSBNK', 'TCNSBK'],
  'The Chandigarh State Co-operative Bank': ['CHDSBK'],
  'The Chandwad Merchants Co-operative Bank': ['CHAMCO'],
  'The Charada Nagrik Sahakari Bank': ['CNSBLH'],
  'The Chitnavispura Sahakari Bank': ['CHSBNK', 'TCSBNK'],
  'The Chittoor District Co-operative Central Bank': ['CTRCCB'],
  'The Chopda Peoples Co-operative Bank': ['CPCBBK'],
  'The Citizens Co-operative Bank Jammu': ['CCBJBK', 'CCBJMU'],
  'The Co-operative Bank of Mehsana': ['TCBMEH'],
  'The Coastal Urban Co-operative Bank': ['TCUBKK'],
  'The Comptrollers Office Co-operative Bank': ['COCBNG'],
  'The Dahod Mercantile Co-operative Bank': ['DMCBNK', 'DMCDHD'],
  'The Dahod Urban Co-operative Bank': ['DAHODB', 'DUBANK'],
  'The Deccan Merchants Co-operative Bank': ['DMCBKL'],
  'The Dharmaj Peoples Co-operative Bank': ['DHARMA'],
  'The District Co-operative Central Bank': ['VSPCCB'],
  'The District Co-operative Central Bank Eluru': ['TDCCBE'],
  'The District Co-operative Central Bank Kakinada': ['KKDCCB'],
  'The District Co-operative Central Bank Khammam': ['DCCBLK'],
  'The Eenadu Co-operative Urban Bank': ['TECUBK'],
  'The Fazilka Central Co-operative Bank': ['CCBFAZ', 'FZKCCB'],
  'The Gandevi Peoples Co-operative Bank': ['TGPCBK'],
  'The Gandhi Co-operative Urban Bank': ['TGCUBK'],
  'The Gandhinagar Urban Co-operative Bank': [
    '112000', 'GUCBSI', 'GUCBSR', 'GUCBTR',
  ],
  'The Goa Urban Co-operative Bank': ['181964', 'GUBNKO', 'GUCBNK'],
  'The Godhra City Co-operative Bank': ['CITYBK'],
  'The Godhra Urban Co-operative Bank': ['GUBANK', 'TGUCBK'],
  'The Gozaria Nagrik Sahakari Bank': ['GNSBLT'],
  'The Greater Bombay Co-operative Bank': ['GBCBBK', 'GBCBBN'],
  'The Gudivada Co-operative Urban Bank': ['GDVBNK'],
  'The Gujarat State Co-operative Bank': ['GSCBBK', 'GSCBNK'],
  'The Guntur District Co-operative Central Bank': ['GTRCCB'],
  'The Gurdaspur Central Co-operative Bank': ['CCBGUR'],
  'The Halol Mercantile Co-operative Bank': ['HMCBNK'],
  'The Hansot Nagrik Sahakari Bank': ['HNSBLH'],
  'The Harij Nagarik Sahakari Bank': ['THNSBL'],
  'The Haryana State Co-operative Apex Bank': ['HARCOB'],
  'The Hasti Co-operative Bank': ['144806', 'HASTIB'],
  'The Honavar Urban Co-operative Bank': ['HUCBNK'],
  'The Hyderabad District Co-operative Central Bank': ['HYDCCB'],
  'The Ichalkaranji Merchants Co-operative Bank': ['IMCOBK'],
  'The Idar Nagrik Sahakari Bank': ['IDRNSB', 'IDRSNB'],
  'The Jalgaon Peoples Co-operative Bank Jalgaon': ['122333', 'JPCBNK'],
  'The Jamnagar Mahila Sahakari Bank': ['TJMSBL'],
  'The Janta Co-operative Bank': ['JCBANK'],
  'The Junagadh Commercial Co-operative Bank': ['151899', 'TJCCBL'],
  'The Kadapa District Co-operative Central Bank': ['KDPCCB'],
  'The Kaira District Central Co-operative Bank': ['KDCBAK'],
  'The Kalna Town Credit Co-operative Bank': ['KTCCBL', 'TKTCCB'],
  'The Kalol Nagarik Sahakari Bank': ['KNSBKL'],
  'The Kalupur Commercial Co-operative Bank': [
    '126000', '126001', '126002', '126003', 'KCBANK', 'KCMEET', 'KCMSGS',
    'KEBANK',
  ],
  'The Kanara District Central Co-operative Bank': ['116001', 'NKDCCB'],
  'The Kangra Central Co-operative Bank': ['KCCBNK', 'KCCBPS'],
  'The Kanyakumari District Central Co-operative Bank': ['KDCCBK'],
  'The Kapadwanj Peoples Co-operative Bank': ['TKPCBL'],
  'The Karad Urban Co-operative Bank': [
    '111917', 'KUBOTP', 'KUBPRO', 'KUBSMS', 'KUBTRN', 'KUCBOT', 'KUCBTR',
  ],
  'The Karnal Central Co-operative Bank': ['KRNDBK'],
  'The Karnataka Central Co-operative Bank': ['KCCDWD'],
  'The Karnavati Co-operative Bank': ['KCOBBK'],
  'The Khambhat Nagarik Sahakari Bank': ['KNSBBK'],
  'The Khattri Co-operative Urban Bank': ['TKCUBL'],
  'The Kheda Peoples Co-operative Bankltd': ['KHEDAB', 'KPCOBL'],
  'The Kodagu District Co-operative Central Bank': ['111014', 'KDGCCB'],
  'The Kodinar Nagrik Sahakari Bank': ['KNSBLK'],
  'The Kodungallur Town Co-operative Bank': ['TKTCBK'],
  'The Kolar District Co-operative Central Bank Kolar': ['DCCBKC', 'KCDCCB'],
  'The Kolhapur Urban Co-operative Bank': ['KUCBNK', 'TKUBNK'],
  'The Kosamba Mercantile Co-operative Bank': ['KMBCBL'],
  'The Koylanchal Urban Co-operative Bank': ['CBSKUB', 'TKUCBL'],
  'The Kranthi Co-operative Urban Bank': ['KCUBNK'],
  'The Krishna District Co-operative Central Bank': ['KRICCB'],
  'The Kukarwada Nagarik Sahakari Bank': ['KNSBNK'],
  'The Kutch Mercantile Co-operative Bank': ['KMCBNK'],
  'The Lakshmi Vilas Bank': ['LVBANK', 'LVBSMS'],
  'The Laxmi Co-operative Bank': ['LAXBNK'],
  'The Limbasi Urban Co-operative Bank': ['LUCBNK', 'TLUBNK'],
  'The Lunawada Nagrik Sahkari Bank': ['LNSBNK'],
  'The Mahabaleshwar Urban Co-operative Bank': ['TMUCBL'],
  'The Maharashtra State Co-operative Bank Mumbai': ['119351', 'MSCBKN'],
  'The Malegaon Merchants Co-operative Bank': ['MAMCOB'],
  'The Malpur Nagrik Sahakari Bank': ['MLBANK'],
  'The Mangalore Catholic Co-operative Bank': ['MCCBNK', 'TMCCOB'],
  'The Mayani Urban Co-operative Bank Mayani': ['MAYANI'],
  'The Meghalaya Co-operative Apex Bank': ['MCAPEX', 'MGSBBK'],
  'The Meghraj Nagarik Sahakari Bank': ['TMNSBL'],
  'The Mehsana Jilla Panchayat Karmachari Co-operative Bank': ['MHSJPN'],
  'The Mehsana Nagarik Sahakari Bank': ['MNSBKL', 'MNSBNK'],
  'The Mehsana Urban Co-operative Bank': [
    'MUCATM', 'MUCBNK', 'MUCCBS', 'MUCINB', 'MUCINF', 'MUCIPO', 'MUCMBS',
    'MUCOTP', 'MUCUPI',
  ],
  'The Merchants Souharda Sahakara Bank Niyamitha': ['TMSCHT'],
  'The Modasa Nagarik Sahakari Bank': ['MODNAG'],
  'The Mogaveera Co-operative Bank': ['184001', 'MOGBNK'],
  'The Municipal Co-operative Bank Mumbai': ['MCBANK', 'MCBBNK'],
  'The Muslim Co-operative Bank': ['MUCOBK'],
  'The Muvattupuzha Urban Co-operative Bank No 556': ['MPAUCB'],
  'The Mysore and Chamarajanagar District Co-operative Central Bank': [
    '107001', 'MCDCCB',
  ],
  'The Nagaland State Co-operative Bank': ['NSCBNK', 'NSTCBL'],
  'The Nainital Bank': ['NTLBNK', 'TNBLTD'],
  'The Nalgonda Dist Co-operative Central Bank': ['DCCBLN'],
  'The Nandura Urban Co-operative Bank Nandura': ['NUCBNK'],
  'The Nasik Jilha Mahila Sahakari Bank': ['NJMSBL', 'TNJMSB'],
  'The Nasik Merchants Co-operative Bank Nashik': ['TNMCBL'],
  'The Nasikroad Deolali Vyapari Sahakari Bank': ['NDVSBK', 'NKRDBK'],
  'The National Central Co-operative Bank': ['BETDBK', 'TNCCBK', 'TNCCBNK'],
  'The National Co-operative Bank': ['123409', 'NCBANK'],
  'The Navnirman Co-operative Bank': ['NVNBNK'],
  'The New Urban Co-operative Bank': ['NUCBRM'],
  'The Nizamabad District Co-operative Central Bank': ['NZBCCB'],
  'The Ottapalam Co-operative Urban Bank': ['OCUBNK'],
  'The Panchkula Central Co-operative Bank': ['PANCHB', 'PANDBK'],
  'The Panchsheel Mercantile Co-operative Bank': ['TPMCBK'],
  'The Panipat Urban Co-operative Bank': ['PANIPT'],
  'The Pragati Urban Co-operative Bank Manmad': ['PUCBLM'],
  'The Raipur Urban Mercantile Co-operative Bank': ['RAIBNK', 'RUMBNK'],
  'The Rajajinagar Co-operative Bank': ['RCBANK'],
  'The Rajapur Sahakari Bank Mumbai': ['RSBANK'],
  'The Rajula Nagarik Sahakari Bank': ['RAJNAG'],
  'The Ranuj Nagrik Sahakari Bank': ['RNUBNK'],
  'The Recharge Bank': ['TRBANK'],
  'The Ropar Central Co-operative Bank': ['CCBROP', 'RPRDBK'],
  'The Sabarkantha District Central Co-operative Bank': ['SBDCBK', 'SKBANK'],
  'The Salem District Central Co-operative Bank': ['SDCCBL'],
  'The Sammco Bank': ['SAMMCO'],
  'The Sangamner Merchants Co-operative Bank Sangamner': ['SMBANK', 'TSMCBK'],
  'The Santrampur Urban Co-operative Bank': ['SUCBLS'],
  'The Sarangpur Co-operative Bank': ['SCOPBL'],
  'The Sardargunj Merchntile Co-operative Bank': ['154987', 'SGMCBL'],
  'The Sarsa People\'s Co-operative Bank': ['SPCBAK'],
  'The Sarvodaya Co-operative Bank Mumbai': ['SAROBK'],
  'The Sarvodaya Sahakari Bank Modasa': ['SSBMOD'],
  'The Sas Nagar Central Co-operative Bank': ['CCBSAS', 'SASCCB'],
  'The Seva Vikas Co-operative Bank': ['SEVABK'],
  'The Siwan Central Co-operative Bank': ['SIWANB', 'SWNCCB'],
  'The Solapur Dist Central Co-operative Bank': ['SDCCBS'],
  'The South Canara District Central Co-operative Bank': ['SCDCCB'],
  'The Ssk Co Opeartive Bankl': ['TSSKBK'],
  'The Sudha Co-operative Urban Bank': ['SCUBNK', 'SUDBNK', 'SUDHAB'],
  'The Surat District Co-operative Bank': ['SUDICO'],
  'The Sutex Co-operative Bank': ['SUTEXB'],
  'The Suvikas Peoples Co-operative Bank': ['SUVKAS'],
  'The Talod Nagrik Sha Bank': ['TNSBLT'],
  'The Tamil Nadu State Apex Co-operative Bank': ['TNSCBK'],
  'The Thane District Central Co-operative Bank': ['115651', 'TDCBNK'],
  'The Tirunelveli District Centre Co-operative Bank': ['TNYCBK'],
  'The Tiruvannamalai Dt Central Co-operative Bank': ['DBKTNM'],
  'The Udaipur Mahila Urban Co-operative Bank': ['UMUCBK', 'UMUCBL'],
  'The Udaipur Urban Co-operative Bank': ['UUCBUD'],
  'The Udupi Co-operative Town Bank': ['180897', 'UCTBNK'],
  'The Unava Nagarik Sahakari Bank': ['UUNSBL'],
  'The Urban Co-operative Bank Dharangaon': ['TUCBLD', 'URBANK'],
  'The Uttarsanda Peoples Co-operative Bank': ['UPCBNK'],
  'The Vadali Nagrik Sahakari Bank': ['VNSBBR'],
  'The Vaidyanath Urban Co-operative Bank': ['VBANKL', 'VUCBNK'],
  'The Vaish Co-operative New Bank': ['VCNBNK'],
  'The Vallbh Vidyanagar Commerical Co-operative Bank': ['VVCCBK'],
  'The Varachha Co-operative Bank': ['VARABK'],
  'The Vejalpur Nagrik Sahakari Bank': ['VNSBLK'],
  'The Vellore District Central Co-operative Bank': ['VCCBNK'],
  'The Vepar Udhyog Vikas Sahkari Bank Jhalod': ['VASBNK', 'VUVSBJ'],
  'The Veraval Peoples Co-operative Bank': ['TVPCBK', 'TVPCBL'],
  'The Vijay Co-operative Bank': ['VCBANK', 'VIJBNK'],
  'The Vsv Co-operative Bank': ['VSVBNK'],
  'The Warangal District Co-operative Central Bank': ['WGLCCB'],
  'The Washim Urban Co-operative Bank Washim': ['WASHIM', 'WUCBKL'],
  'The Yavatmal Urban Co-operative Bank': ['TYUBNK', 'YUCBLY'],
  'Thrissur District Co-operative Bank': ['TDCBBK'],
  'Tumkur Veerashaiva Co-operative Bank': ['TVCBNK'],
  'U P Postal Primary Coopreative Bank': ['PSTBNK'],
  'UCO Bank': ['UCOBNK'],
  'Ujjain Paraspar Sahakari Bank Mydt': ['UPSBBK'],
  'Ujjivan Small Finance Bank': ['UJJIVN', 'UJVNBP'],
  'Uma Co-operative Bank': ['UMABNK', 'UMACOB'],
  'Union Bank of India': ['100026', 'UNIONB'],
  'United Bank of India': [
    '111666', 'AGVBNK', 'AGVCBS', 'BGVBNK', 'BGVCBS', 'MRBANK', 'MRBCBS',
    'TGBANK', 'TGBCBS', 'UBIBNK', 'UBISMS',
  ],
  'Unjha Nagarik Sahakari Bank': ['UNSBNK'],
  'Urban Co-operative Bank Dehradun': ['UCBANK', 'UCBDHN'],
  'Utkal Grameen Bank': ['UKGBBK', 'UTKLGB'],
  'Utkarsh Small Finance Bank': ['UTKBNK', 'UTKMIS', 'UTKSFB'],
  'Uttar Bihar Gramin Bank': ['UBGBNK'],
  'Uttarakhand Gramin Bank': ['UGBBNK', 'UTGBBK'],
  'Uttarakhand State Co-operative Bank': ['USCBNK', 'UTKSBK'],
  'Uttarbanga Kshetriya Gramin Bank': ['UBKGBK', 'UBKGBM'],
  'Uttarkashi Zila Sahkari Bank': ['UKASHI', 'UTKDBK'],
  'Valayam Service Co-operative Bank': ['VALSCB'],
  'Valmiki Urban Co-operative Bank Lrd Pathri': ['VUCBKP'],
  'Vasai Vikas Sahakari Bank': ['VVSBNK'],
  'Vasundhara Mahila Nagari Sahakari Bank Ambajogai': ['VMNBNK'],
  'Veerashaiva Sahakari Bank': ['VSBNKL'],
  'Vidyanand Co-operative Bank Solapur': ['VIDYBK'],
  'Vikas Sahakari Bank Solapur': ['185241', 'VKSBNK'],
  'Vikas Souharda Co-operative Bank': ['VIKASB', 'VIKBNK'],
  'Vita Merchant Co-operative Bank': ['VMCBDC'],
  'Wana Nagarik Sahakari Bank': ['WANABK'],
  'Wayanad District Co-operative Bank': ['WDCBNK', 'WYDDCB'],
  'YES Bank': ['YESBCC', 'YESBCM', 'YESBNK', 'YESPAY'],
  'Yadrav Co-operative Bank Yadrav': ['YDRVBK'],
  'Zila Sahakari Bank Hardwar': ['HARDBK', 'HARIDC'],
  'Zila Sahkari Bank Bulandshar': ['BULAND'],
  'Zila Sahkari Bank Garhwal(kotdwar)': ['GARHBK', 'KTWBNK'],
  'Zila Sahkari Bank Ghaziabad': ['DCBGZB', 'ZSBGZB'],
  'Zila Sahkari Bank Jhansi': ['ZSBJBK'],
  'Zila Sahkari Bank Mathura': ['MZSBNK'],
  'Zila Sahkari Bank Meerut': ['DCBMRT', 'ZSBMRT'],
  'Zila Shakari Bank Rampur': ['RAMDCC', 'ZSBRMP'],
};
